### ISSUE TITLE
doesn't this script support cn-northwest-1 region

### ISSUE THREAD

**Issue by aqiao** [lianghong/delete_vpc#13]
aqiao@aqiaodeMacBook-Pro delete_vpc % ./delete_vpc.sh --region cn-northwest-1 --vpc-id vpc-05e1867fe5a9c47ce
*** Are you sure to delete the VPC of vpc-05e1867fe5a9c47ce in cn-northwest-1 (y/n)? y
Process of ELB ...
Process of EC2 instance(s) ...
Process of NAT Gateway ...
    waiting for state of deleted
Process of VPN connection ...

An error occurred (UnsupportedOperation) when calling the DescribeVpnConnections operation: The functionality you requested is not available in this region.
Process of VPN Gateway ...
Process of VPC Peering ...
Process of VPC endpoints ...
Process of Egress Only Internet Gateway ...
Process of Network ACLs ...
Process of Elastic IP ...
Process of Network Interface ...
    detach Network Interface of eni-0d857b4625d2957cc
network attachment is ela-attach-00eb2f04b753bbaf5

**Comment by lianghong** [comment]
For china regions (cn-northwest-1|cn-north-1), the step of Delete VPN connection and  Delete VPN Gateway will be ignored. Please check new release.

**Comment by aqiao** [comment]
@lianghong ，thanks for your response, will check it later
