### ISSUE TITLE
BJS删除VPC失败，无法删除安全组SecurityGroup 导致的。

### ISSUE THREAD

**Issue by liangyimingcom** [lianghong/delete_vpc#2]
✘ iMac  ~/Dropbox/ssh/delete_vpc  ./delete_vpc.sh cn-north-1 vpc-68d1920c
Process of EC2 instance ...
Process of NAT Gateway ...
    waiting for state of deleted
Process of VPN connection ...

An error occurred (UnsupportedOperation) when calling the DescribeVpnConnections operation: The functionality you requested is not available in this region.
Process of VPN Gateway ...
Process of VPC Peering ...
Process of VPC endpoints ...
Process of Egress only internet gateway ...
Process of Network ACLs ...
Process of Security Group ...
    delete Security group of sg-14872d73

**An error occurred (DependencyViolation) when calling the DeleteSecurityGroup operation: resource sg-14872d73 has a dependent object**

BJS删除VPC失败，无法删除安全组SecurityGroup 导致的。
请问：某些安全组绑定在ENI上，各种方法都试过了，ENI无法删除，有解吗？

谢谢。

**Comment by lianghong** [comment]
Solved, please try the new version.
