### ISSUE TITLE
Unknown options: --filters, Name=attachment.vpc-id

### ISSUE THREAD

**Issue by tho-can-code** [lianghong/delete_vpc#6]
Hi @lianghong,

I got the error

```
Process of Egress Only Internet Gateway ...
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --filters, Name=attachment.vpc-id,Values=vpc-xxx
Process of Network ACLs ...
```

Could you please check it?

**Comment by lianghong** [comment]
![result](https://user-images.githubusercontent.com/3388147/130622592-24576160-1318-4ec5-a895-8c19dc9e64de.jpg)
I tried and couldn't find the problem. Can you give me more details?

**Comment by tho-can-code** [comment]
@lianghong It because of my AWS environment. Please ignore it. Thank you so much.
